// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VIgiAQ4Ig3xWPdastNvVZXLxsX_S2u0',
    appId: '1:198328224777:web:82dddc1ee19379c8dffcd8',
    messagingSenderId: '198328224777',
    projectId: 'wirelesspj-a2336',
    authDomain: 'wirelesspj-a2336.firebaseapp.com',
    storageBucket: 'wirelesspj-a2336.appspot.com',
    measurementId: 'G-7BSY34QW8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtV2uthbWx6AhkQ07V6w-yOhGLPURxcB4',
    appId: '1:198328224777:android:26ca1fcd677d3fe9dffcd8',
    messagingSenderId: '198328224777',
    projectId: 'wirelesspj-a2336',
    storageBucket: 'wirelesspj-a2336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVcuROFgSfKZSckrTBDTYPmIZv3vMX6JY',
    appId: '1:198328224777:ios:78ddbd69122fdf26dffcd8',
    messagingSenderId: '198328224777',
    projectId: 'wirelesspj-a2336',
    storageBucket: 'wirelesspj-a2336.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVcuROFgSfKZSckrTBDTYPmIZv3vMX6JY',
    appId: '1:198328224777:ios:88688870d33a1580dffcd8',
    messagingSenderId: '198328224777',
    projectId: 'wirelesspj-a2336',
    storageBucket: 'wirelesspj-a2336.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
